- name: Crea VCN
  hosts: localhost
  connection: local

  vars_files: vault.yaml


  tasks:
#    - block:
        - name: Crea VCN
          oracle.oci.oci_network_vcn:
            compartment_id: "{{ compartment_ocid }}"
            display_name: "{{ vcn_name }}"
            dns_label: " {{ vcn_dns_label }}"
            cidr_block: "{{ vcn_cidr_block }}"
          register: resultado

#        - set_fact:
#             vcn_id: "{{ resultado.autonomous_database.id }}"

#        - assert:
#            that:
#              - resultado.autonomous_database.lifecycle_state == "AVAILABLE"

#        - name: Lista Todas las Instancias de ADB
#          oracle.oci.oci_database_autonomous_database_facts:
#             compartment_id: "{{ compartment_ocid }}"
#             display_name: "{{ display_name }}"
#          register: resultado

#        - name: Valida si Existe Nueva Instancia
#          assert:
#             that:
#                - resultado.autonomous_databases[0].display_name == display_name
#      rescue:

#        - fail:
#            msg: "ERROR, No se logro Crear Instancia ADB."
