- name: Modifica Default Route
  hosts: localhost
  connection: local

  vars_files: vault.yaml

  tasks:
    - block:
        - name: Lista Todas las VCNs
          oracle.oci.oci_network_vcn_facts:
             compartment_id: "{{ compartment_ocid }}"
             display_name: "{{ display_name }}"
          register: resultado

        - name: Valida si Existe la VCN
          assert:
             that:
                - resultado.vcns[0].display_name == display_name

        - set_fact:
             default_route_table_id: "{{ resultado.vcns[0].default_route_table_id }}"
             
        - name: Lista Todos los Internet Gateway
          oracle.oci.oci_network_internet_gateway_facts:
            compartment_id: "{{ compartment_ocid }}"
            display_name: "{{ display_name }}"
          register: resultado

        - set_fact:
             network_entity_id: "{{ resultado.vcns[0].internet_gateway }}"


        - name: Actualiza Default Route para Salida a Internet
          oracle.oci.oci_network_route_table:
            id: "{{ default_route_table_id }}"
            route_rules:
            - cidr_block: '0.0.0.0/0'
              network_entity_id: 
          register: resultado

        - set_fact:
            rt_id: "{{ resultado.route_table.id }}"


        - name: Valida Creacion de Internet Gateway
          assert:
             that:
      rescue:

        - fail:
            msg: "ERROR, No se Logro Crear Internet Gateway."
