- name: Elimina Salida a Internet Desde Default Route
  hosts: localhost
  connection: local

  vars_files: vault.yaml

  tasks:
    - block:
        - name: Lista Todas las VCNs
          oracle.oci.oci_network_vcn_facts:
             compartment_id: "{{ compartment_ocid }}"
             display_name: "{{ display_name }}"
          register: resultado

        - name: Valida si Existe la VCN
          assert:
             that:
                - resultado.vcns[0].display_name == display_name

        - set_fact:
             default_route_table_id: "{{ resultado.vcns[0].default_route_table_id }}"
             
        - name: Lista Todos los Internet Gateway
          oracle.oci.oci_network_internet_gateway_facts:
            compartment_id: "{{ compartment_ocid }}"
            display_name: "{{ ig_name }}"
          register: resultado

        - set_fact:
             network_entity_id: "{{ resultado.internet_gateways[0].id }}"


        - name: Elimina Default Route para Salida a Internet
          oracle.oci.oci_network_route_table:
            id: "{{ default_route_table_id }}"
            purge_route_rules: true
#            delete_route_rules: true

      rescue:

        - fail:
            msg: "ERROR, No se Logro Eliminar Default Route."
